# vim:ft=kitty

## name:     Catppuccin-Mocha
## author:   Pocco81 (https://github.com/Pocco81)
## license:  MIT
## upstream: https://github.com/catppuccin/kitty/blob/main/mocha.conf
## blurb:    Soothing pastel theme for the high-spirited!


## #00a2e8 Kris 
## #ae67af Susie 
## #4ecc8f Ralsei 

# The basic colors
foreground              #CDD6F4
background              #040006
selection_foreground    #1E1E2E
selection_background    #7e57c2

# Cursor colors
cursor                  #7e57c2
cursor_text_color       #000000

# URL underline color when hovering with mouse
url_color               #7e57c2

# Kitty window border colors
active_border_color     #7e57c2
inactive_border_color   #1e004f
bell_border_color       #00a2e8

# OS Window titlebar colors
wayland_titlebar_color system
macos_titlebar_color system

# Tab bar colors
active_tab_foreground   #1a003e
active_tab_background   #7e57c2
inactive_tab_foreground #00a2e8
inactive_tab_background #1e004f
tab_bar_background      #000000

# Colors for marks (marked text in the terminal)
mark1_foreground #000000
mark1_background #00a2e8
mark2_foreground #000000
mark2_background #ae67af
mark3_foreground #000000
mark3_background #4ecc8f

# The 16 terminal colors

# black
color0  #000000
color8  #7292a0

# red
color1 #F38BA8
color9 #F38BA8

# green
color2  #4ecc8f
color10 #4ecc8f

# yellow
color3  #F9E2AF
color11 #F9E2AF

# blue
color4  #00a2e8
color12 #00a2e8

# magenta
color5  #ae67af
color13 #ae67af

# cyan
color6  #94E2D5
color14 #94E2D5

# white
color7  #BAC2DE
color15 #A6ADC8
